Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,55 +2,11 @@ on:
   push:
     branches:
       - "*"
-      - "!main"
+      - "!stable"
 
 name: 🔥 Test Workflow
 jobs:
-  phpstan:
-    name: 🚦 PHPStan analysis
-    runs-on: ubuntu-latest
-    steps:
-      - name: 🐙 Git checkout
-        uses: actions/checkout@v4
-      - name: 🛠️ Install dependencies
-        run: composer install --no-interaction
-      - name: 🚦 Analyze with PHPStan
-        run: composer phpstan
-  phpunit:
-    name: ✅ Run phpunit
-    runs-on: ubuntu-latest
-    services:
-      mysql:
-        image: mysql:8.0
-        env:
-          MYSQL_ROOT_PASSWORD: testing
-          MYSQL_DATABASE: larapulse
-        ports:
-          - 3306:3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
-    steps:
-      - name: 🐙 Git checkout
-        uses: actions/checkout@v4
-      - name: 🛠️ Install dependencies
-        run: composer install --no-interaction
-      - name: 📑 Set up php
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: 8.1
-      - name: 📄 Create environment
-        run: cp .env.example .env
-      - name: 🔑 Generate app key
-        run: php artisan key:generate
-      - name: 💽 Running database migrate
-        run: php artisan migrate --env=testing
-      - name: 🌱 Run database seeder
-        run: php artisan db:seed --class='Database\Seeders\TestingSeeder' --env=testing
-      - name: 🗺️ Check routes
-        run: php artisan route:clear && php artisan route:list
-      - name: ✅ Run php tests
-        run: vendor/bin/phpunit
   tagging:
-    needs: [phpstan, phpunit]
     name: 🏷️ Tagging the app
     runs-on: ubuntu-latest
     steps:
@@ -67,7 +23,7 @@ jobs:
           PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
           PRESERVE_VERSION: 5
   create-pr:
-    needs: [phpstan, phpunit, tagging]
+    needs: tagging
     name: 🔄 Create Pull Request
     runs-on: ubuntu-latest
     environment: testing
@@ -87,7 +43,7 @@ jobs:
           CURRENT_BRANCH=$(echo "${GITHUB_REF}" | awk -F'/' '{print $3}')
 
           # Check if a pull request already exists
-          EXISTING_PR=$(gh pr list --state open --base main --head "${CURRENT_BRANCH}" --json number | jq -r '.[0].number')
+          EXISTING_PR=$(gh pr list --state open --base stable --head "${CURRENT_BRANCH}" --json number | jq -r '.[0].number')
 
           # If a pull request exists, exit the workflow
           if [[ "$EXISTING_PR" == null ]]; then
@@ -95,13 +51,38 @@ jobs:
             CURRENT_DATE=$(TZ='Asia/Jakarta' date +'%d-%m-%Y %H:%M')
 
             # Create a pull request with date and time in the title
-            PR_TITLE="[$CURRENT_DATE] $CURRENT_BRANCH - Request merge $CURRENT_BRANCH to main branch"
+            PR_TITLE="[$CURRENT_DATE] $CURRENT_BRANCH - Request merge $CURRENT_BRANCH to stable branch"
 
-            gh pr create \
-              --base main \
-              --head "${CURRENT_BRANCH}" \
-              --title "${PR_TITLE}" \
-              --body "Automated pull request from ${CURRENT_BRANCH} to main branch"
+            git fetch origin stable
+            fetch_exit_code=$?
+
+            git fetch origin "${CURRENT_BRANCH}"
+            fetch_branch_exit_code=$?
+
+            if [ $fetch_exit_code -ne 0 ]; then
+              echo "Error fetching 'stable' branch from origin."
+              exit 0  # Script continues despite the error
+            fi
+
+            if [ $fetch_branch_exit_code -ne 0 ]; then
+              echo "Error fetching '${CURRENT_BRANCH}' branch from origin."
+              exit 0  # Script continues despite the error
+            fi
+
+            # Check if the branch exists in the remote repository
+            if ! git ls-remote --exit-code origin "${CURRENT_BRANCH}"; then
+              echo "'${CURRENT_BRANCH}' branch does not exist in the remote repository. $?"
+            fi
+
+            if git diff --quiet origin/stable origin/"${CURRENT_BRANCH}"; then
+              echo "No commits between branches. Skipping pull request creation."
+            else
+              gh pr create \
+                --base stable \
+                --head "${CURRENT_BRANCH}" \
+                --title "${PR_TITLE}" \
+                --body "Automated pull request from ${CURRENT_BRANCH} to stable branch"
+            fi
           else
             echo "Pull request ${CURRENT_BRANCH} already exists ${EXISTING_PR}. Skipping PR creation."
             exit 0
